spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/booking_health_care
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    servlet:
      multipart:
        max-file-size: 10MB
jwt:
  privateKey: YOpwYOb8kB04/1U5AUY7EsA7NXdHH8PQLwW/t/280idMbD2RUd+Mrzz7incpwSluLrCUadgo82GpSPUxeyIkXA==
  expiration: 36000 #10 * 60 * 60 (10 hours)
  longExpiration: 604800 #7 * 24 * 60 * 60 (7 days)
  defaultPassword: 123@456

fileUpload:
  rootPath: C:\Users\NC\Desktop\upLoads
#server:
#    port: 8081